
server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://macro:123456@localhost:8004/eureka/
zuul:
  routes:
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  #zuul给请求头加上debug  X-Zuul-Debug-Header 之后再请求路径上带上参数可以打印过滤器信息 http://192.168.1.47:8801/userService/user/2?debug=true或者配置zuul-request-debug: true给所有请求都带上debug信息
  include-debug-header: true
#  add-host-header: true #设置为true重定向是会添加host请求头
#  prefix: /proxy  #给网关路由添加前缀
#  ignored-services: user-service,feign-service #关闭默认路由配置
#  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
#  add-host-header: true #设置为true重定向是会添加host请求头
#开启查看路由的端点  http://localhost:8801/actuator/routes
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

#开启debug日志级别
#logging:
#  level:
#    com.netflix: DEBUG

# 禁用zuul过滤器
#zuul:
#  PreLogFilter:
#    pre:
#      disable: true
